### ISSUE TITLE
disable HTML5 autocomplete on the tag input box

### ISSUE THREAD

**Issue by blaenk** [clvrobj/Pinboard-Plus#28]
When typing a tag name into the tag input box, I see two autocomplete pop-ups: 1) the custom autocomplete pop-up of this extension and 2) the HTML5 autocomplete. Please disable the second one, since it doesn't work well and covers up (appears on top of) the custom autocomplete pop-up you created.

This can be done by simply adding the `autocomplete="off"` attribute to the tag input box.

**Comment by brunorsini** [comment]
I have the very same problem and agree it's very annoying.

On Sat, Dec 19, 2015 at 4:24 AM, Jorge Israel Peña <notifications@github.com

**Comment by clvrobj** [comment]
Fixed in #32
