### ISSUE TITLE
API errors aren't communicated to users

### ISSUE THREAD

**Issue by NelsonMinar** [clvrobj/Pinboard-Plus#36]
Thanks for Pinboard Plus! I use it several times a day to feed a blog and twitter account. It's great!

I have a UI problem though; if posting a link to the Pinboard API fails, there's no error communicated to the user. I've lost a bunch of bookmarks this way. Like today three bookmarks failed to show up on Pinboard. I finally figured it out when I opened the extension's `background.html` and found Pinboard API timeouts on the console.

The extension can't do anything about the timeouts, but it would be nice if it could warn me my link got lost. I recognize signaling an error is tricky, particularly the way the Pinboard window is an ephemeral popup. But it seems important to me.

Thanks!
  nelson

**Comment by clvrobj** [comment]
Thanks @NelsonMinar for using the extension.
The problem you have is just the point what I want to improve, I plan to work on it soon.

**Comment by clvrobj** [comment]
2.11.1 published in the chrome store, one improvement is that user will be notified in the popup window when the following errors occur: connection failed, API error and Token expire(auth error).
@NelsonMinar hope it works for you.

**Comment by NelsonMinar** [comment]
Thank you so much!

**Comment by NelsonMinar** [comment]
Just wanted to say the new code seems to be working well. There've been a few periods of API outages at Pinboard and the extension has communicated them to me effectively. Thanks!

**Comment by clvrobj** [comment]
Great to hear that! I am closing this issue now.
