### ISSUE TITLE
Tab auto-complete only works on second load

### ISSUE THREAD

**Issue by blaenk** [clvrobj/Pinboard-Plus#39]
For a while now, when I open the pinboard popup by clicking on the icon, typing tags doesn't show the autocomplete unless and until I close it, then open the popup again.

**Comment by clvrobj** [comment]
Thanks for reporting this.
I've aware this, will try to reproduce and improve it.

**Comment by blaenk** [comment]
Thanks a ton. I absolutely love this extension by the way, it's the best Pinboard one by far.

I tried to find more information to give you but I couldn't figure it out. I think maybe the tags are fetched without providing a callback to do something with them once they're loaded, but I'm not positive.

I hope you can figure it out. Good luck!

**Comment by clvrobj** [comment]
I think I've spotted the cause and done the workaround, it should be released by this week as I need to do some test.
