### ISSUE TITLE
Tag Suggestions Always the Same

### ISSUE THREAD

**Issue by cmesoar** [clvrobj/Pinboard-Plus#43]
Great extension - thanks!
However, it seems that every pin I make regardless of the website I am on always suggest the same set of tags! And the tags are seemingly totally unrelated to the page. This is what it suggests: ifttt twitter facebook WSH objective-c twitterlink 1960s @codepo8 Aiviq art

When I go to pinboard, the links are saved with the tags I've entered just fine, so it appears to be functioning correctly against the pinboard api

**Comment by clvrobj** [comment]
Thanks for the reporting the issue.

The tags displayed in the extension are recommended tags by Pinboard base on the current URL.
Those tags you mentioned I believe are the default tags returned by the Pinboard API, which are displayed when the URL is new or somehow, not enough info to recommend tags for it.

**Comment by ventz** [comment]
It would be great if the "keywords" meta tag could be used (maybe combined with some popularity?) from the page itself.

I've actually noticed that currently the tags are in one of two extremes: either incredibly accurate (for tech stuff especially, ex: javascript/nodejs, etc), or incredibly inaccurate :)

**Comment by ventz** [comment]
I have a patch that will do just this ^ pull the keyword meta value from pages that have it available (ex: nytimes) and add that to the "suggested keywords" list.

**Comment by ventz** [comment]
Created a PR (https://github.com/clvrobj/Pinboard-Plus/pull/46) that will pull local meta keywords when available, in order to provide better/more accurate suggested keywords.

**Comment by clvrobj** [comment]
Thanks for the contribution from @ventz ! The PR #47 has been merged and deployed to the Chrome web store.
