### ISSUE TITLE
Getting message "The post Sentry is not saved. Error" when creating a bookmark

### ISSUE THREAD

**Issue by janwerner** [clvrobj/Pinboard-Plus#44]
Been using Pinboard Plus on a daily basis for years. Started to get this error when creating a bookmark:

![image](https://user-images.githubusercontent.com/1213706/45928295-8e8a2e00-bf41-11e8-980f-b107d0a4e583.png)

Bookmarking works nonetheless. Would be great if you could take a look. Thanks for your work!

**Comment by clvrobj** [comment]
Hi @janwerner thanks for raising this! 
The error is just for reminding the user that there was one post('Sentry' in your case) has failed to save to Pinboard. 
Did you try closing the banner by clicking the 'x' button on the right and see whether the error show again or not?

**Comment by janwerner** [comment]
@clvrobj Hi, sorry, you're right. It appeared a gain twice, but now it seems to be Ok again. Thanks :)
