### ISSUE TITLE
Stopped working. timeout when trying to log in.

### ISSUE THREAD

**Issue by briantully** [clvrobj/Pinboard-Plus#54]
This stopped working recently where saving a pin or typing tags would just freeze the interface and nothing ever gets saved to pinboard.

I tried disabling and re-enabling the extension with no luck.

I tried logging out and back in through the extension, but when I enter my API key and submit it just hangs and times out. So I can't log in to Pinboard via the extension.

FYI Chrome version is `Version 78.0.3894.0 (Official Build) canary (64-bit)`

Is this extension still being maintained? I see there's a pull request from May that hasn't been merged yet, so maybe this has been abandoned?

**Comment by clvrobj** [comment]
I tried but can't reproduce it.
I think the issue likely related to the API, not on the extension.
Are you still facing the issue?
